<!DOCTYPE html>
<html>
    <head>
        <title>30 Days of JavaScript</title>
    </head>

    <body>
        <h1>Day 13: Error Handling</h1>
        <ul>
            <p>JavaScript is a loosely-typed language. Some times you will get a runtime
                error when you tru to access an undefined variable or call undefined function etc.
            </p>
            <p>    
                JavaScript similar to Python or Java provides an error-handling mechanism to catch 
                runtime errors using try-catch-finally block.
            </p>
            <pre>try {
    // code that may throw an error
} catch (err) {
    // code to be executed if an error occurs
} finally {
    // code to be executed regardless of an error occurs or not.
}</pre>
        <p>
            <b>try:</b> wrap suspicious code that may throw an error in try block.
                The try statement allows us to define a block of code the be tested for errors while
                it is being executed.
        </p>
        <p>
            <b>catch:</b> write code to do something in catch block when an error occurs. The catch block can have
            parameters that will give you error information. Catch block is used to log an error or display specific
            messages to the user.
        </p>
        <p>
            <b>finally:</b> finally block will always be executed regardless of the occurrence of an error. 
            The finally block can be used to complete the remaining task or reset variables that might have changed before error occurred in try block.
        </p>
        </ul>
        <script src="./Error.js"></script>
    </body>
</html>